name: group_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  animations: ^2.0.7
  simple_animations: ^5.0.0+3
  flutter:
    sdk: flutter
  flutter_vector_icons: ^1.0.0
  flutter_easyloading: ^3.0.5
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  number_text_input_formatter: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
